### PR TITLE
Sanitize/encode inputs for creating products to prevent tag injection.

### PR DESCRIPTION
**Pull request by gwsii**
Online examples of how to accomplish this relied on jQuery, but the HTML encoding can be done with just the document interface. Now, whatever tags the user enters as text is simply displayed as tags. Should mitigate the issue of injecting tags into the data and having the browser interpret those tags as valid markup.

Check out [this product](https://greg.hello-retail.biz/#/category/CAT%20%3Cb%3EOF%20EVIL!%20to%20make%20all%20things%20bold!) for an example of how this looks.

### CODE REVIEW

**Comment by erikerikson** [comment]
I have concerns with this approach I'd like to run by you.  Let's discuss tomorrow when I'm back in?

**Comment by gwsii** [comment]
Sure. There's a bit more to be done to secure on the server-side, but happy to discuss.

**Comment by gwsii** [comment]
Good Q on how it will affect the rest of the system. Generally, since the user could already type whatever they wanted into the text inputs and it would move through the system without any issues, already means that we should be confident that the *HTML* encoded `(<,>,&) --> (&lt;, &gt;, &amp;)` data should flow through the system in the same way. However, there are effects on the system due to this encoding, including 1) a slight bloat to any user data containing symbols we encode, 2) any data containing encoded entities will look funky if rendered in plain text and finally 3) if search functionality or other such is implemented then the data may need to be decoded before searched/indexed to find the `>,< or &` characters.

**Comment by gwsii** [comment]
Per our offline conversation, rather than plug this hole on the input side, we'll fix it at display-time.

**Comment by gwsii** [comment]
LOL. Took the time to validate that this is really an issue, after reading about React JS handling of this, it's not a problem. Closing PR.

**Pull request closed without merging**
