### PR TITLE
Add length constraints to product-create schema. Fix for lint.

### PR DESCRIPTION
**Pull request by gwsii**
A quick fix to limit the message payload.

### CODE REVIEW

**Comment by TeamJetpack** [comment]
Thanks for doing this.  What about the ids in the product purchase or fields in the photographer schemas?

**Comment by laurwang** [comment]
Sorry, no idea I was signed in as Team Jetpack.

**Comment by erikerikson** [comment]
There's more than Lauren mentions

**Comment by gwsii** [comment]
Closing as a distraction.

**Pull request closed without merging**
