### PR TITLE
Utf fix eng 2216

### PR DESCRIPTION
**Pull request by gwsii**
Appears to be the correct fix for the null character issue. 

{{
2017-04-05T00:59:59.251Z	988e20db-f851-471b-9298-f70c7bb631c0
{ "errorMessage": "Unexpected token \u0000", "errorType": "SyntaxError", "stackTrace": [ "Object.parse (native)", "impl.putProduct.module.exports.processKinesisEvent.complete (/var/task/catalog.js:315:36)" ] }
}}

Meaning that client-side null characters were likely not the issue. When I discussed this with Erik today, we considered that text encoding may be the problem. I decided to switch the decoding of the message from 'ascii' to 'utf8' and this resolved fixed the problem, allowing the new products to be added.

### CODE REVIEW

**Comment by gwsii** [comment]
Changed base branch from master to develop. That's better! :D

**Comment by laurwang** [comment]
When you say you switched the decoding, do you mean that's in code that Erik will check in separately?  If so, perhaps add that code or give a pointer to which files will need a change to support this fix.

**Comment by erikerikson** [comment]
That change is on your branch or in a comment @laurwang

**Comment by erikerikson** [comment]
my comment here: https://github.com/Nordstrom/hello-retail/pull/66#discussion_r109808277
called out explicitly below it: https://github.com/Nordstrom/hello-retail/pull/66#discussion_r109809822

**Comment by laurwang** [comment]
I updated the branch for #66 . What I was trying to say is that the place where the fix is needed seems to be related to the product catalog, given the page that is in this PR.  My PR was just about your photo-execute bit, so is the necessary block also in (or needed) for product-catalog.

**Comment by erikerikson** [comment]
Ah!  Thanks Lauren.  Yes.  Just a second...

**Comment by erikerikson** [comment]
okay, added the encoding (and other bug fixes) on https://github.com/Nordstrom/hello-retail/pull/68 and PR'd onto @laurwang 's PR.

**Comment by laurwang** [comment]
I merged #68 into mine.  Please have a look at #66 now.

**Pull request merged**
