### PR TITLE
Refactor lab with web fixes

### PR DESCRIPTION
**Pull request by gwsii**
Adds Home icon.
Fixes login issues.
Improves layout for mobile.

NOTE: Same changes as previous PR, but now targeting develop since refactor-lab has been merged.

### CODE REVIEW

**Comment by erikerikson** [comment]
I think you mean `develop`, not `master` 😄

**Comment by gwsii** [comment]
Need to figure out why this is not a clean merge.

**Comment by erikerikson** [comment]
perhaps fetch the latest of develop and merge it into your branch?

**Pull request closed without merging**
